version: "2"

services:
  webserver:
    volumes:
      - "./../app/:/var/www/"
  php:
    volumes:
      - "./Docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./Docker/php/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - "./../app/:/var/www/"
    links:
      - "mailcatcher"
  mailcatcher:
    image: "schickling/mailcatcher"
    environment:
      VIRTUAL_HOST: "mailcatcher.docker"
      VIRTUAL_PORT: 1080
