version: "2"

volumes:
  project-data:
    driver: local

services:
  webserver:
    volumes:
      - "project-data:/var/www/"
  php:
    volumes:
      - "./Docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./Docker/php/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - "project-data:/var/www/"
    links:
      - "mailcatcher"
  mailcatcher:
    image: "schickling/mailcatcher"
    ports:
      - "10${PORTSUFFIX}:1080"
  rsync:
    image: "eugenmayer/rsync"
    ports:
      - "8${PORTSUFFIX}:873"
    environment:
      VOLUME: "/var/www"
      OWNER: 1000
      GROUP: 33
    volumes:
      - "./Files/rsyncd.conf:/etc/rsyncd.conf"
      - "project-data:/var/www/"
